In [60]:
import pandas as pd
import matplotlib.pyplot as plt
import scipy.cluster.hierarchy as sch
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import AgglomerativeClustering
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from pickle import dump, load

In [2]:
college_data = pd.read_csv("college_list.csv")
college_data

                                          College_Name  ...  Infrastructure_Score
0     Indian Institute of Technology Madras - Campus 1  ...                     8
1    National Institute of Technology Trichy - Camp...  ...                     7
2                   Anna University Chennai - Campus 1  ...                     9
3                 PSG College of Technology - Campus 1  ...                     8
4        Coimbatore Institute of Technology - Campus 1  ...                     9
..                                                 ...  ...                   ...
495     Thiagarajar College of Engineering - Campus 17  ...                     5
496  Bannari Amman Institute of Technology - Campus 17  ...                     7
497  Sri Krishna College of Engineering and Technol...  ...                     3
498             Sona College of Technology - Campus 17  ...                     6
499        Karpagam College of Engineering - Campus 17  ...                     8

[500 rows x 6 columns]

In [9]:
X = college_data.drop("College_Name", axis=1)

In [5]:
college_data.shape

(500, 6)

In [6]:
college_data.describe()

       Student_Faculty_Ratio  Annual_Fees_INR  Placement_Percentage  Average_Package_LPA  Infrastructure_Score
count             500.000000       500.000000            500.000000           500.000000             500.00000
mean               18.084000    138763.710000             69.000000             6.991720               5.97600
std                 6.683283     63928.678815             17.193465             2.917991               2.00486
min                 8.000000     30404.000000             40.000000             2.000000               3.00000
25%                12.000000     82610.500000             53.750000             4.472500               4.00000
50%                18.000000    140290.500000             69.000000             7.155000               6.00000
75%                24.000000    193422.000000             84.000000             9.432500               8.00000
max                29.000000    249930.000000             99.000000            11.990000               9.00000

In [7]:
college_data.dtypes

College_Name                 str
Student_Faculty_Ratio      int64
Annual_Fees_INR            int64
Placement_Percentage       int64
Average_Package_LPA      float64
Infrastructure_Score       int64
dtype: object

In [13]:
scaler = StandardScaler()
scaled_X = scaler.fit_transform(X)
scaled_X = pd.DataFrame(scaled_X)
scaled_X

            0         1         2         3         4
0   -0.611689 -0.402753 -0.582199  0.757539  1.010558
1    1.335411 -0.356452 -0.116440 -1.345326  0.511270
2    0.586526 -1.421892 -1.106178 -1.232121  1.509845
3   -0.012581 -1.110515 -1.513717 -0.806745  1.010558
4   -0.461912 -0.596945 -0.873298 -0.799884  1.509845
..        ...       ...       ...       ...       ...
495 -0.162358 -0.507960 -0.756858  0.802135 -0.487305
496 -0.911243 -1.560372  0.407539 -1.156651  0.511270
497 -0.312135  0.946035 -0.291099 -1.067459 -1.485880
498 -1.210797 -1.446412  0.465759  0.795274  0.011983
499  0.886080  0.210027  1.630157 -1.177234  1.010558

[500 rows x 5 columns]

In [16]:
scaled_X.mean(), scaled_X.std()

(0    7.105427e-17
 1    1.278977e-16
 2   -7.105427e-18
 3    3.259615e-16
 4   -8.881784e-18
 dtype: float64,
 0    1.001002
 1    1.001002
 2    1.001002
 3    1.001002
 4    1.001002
 dtype: float64)

In [18]:
agg_model = AgglomerativeClustering(n_clusters=4,linkage='ward')
clusters = agg_model.fit_predict(scaled_X)
clusters

array([2, 0, 0, 0, 0, 1, 3, 1, 2, 3, 1, 3, 0, 2, 0, 1, 2, 0, 3, 3, 1, 2,
       2, 1, 3, 1, 0, 1, 0, 0, 0, 2, 3, 2, 2, 1, 3, 1, 2, 3, 0, 3, 1, 1,
       2, 0, 3, 0, 1, 0, 0, 3, 1, 2, 1, 1, 2, 0, 0, 2, 2, 2, 1, 0, 2, 1,
       1, 1, 3, 0, 0, 1, 1, 1, 3, 0, 3, 1, 0, 0, 1, 1, 1, 3, 2, 3, 1, 2,
       0, 2, 2, 2, 0, 0, 0, 1, 1, 2, 3, 2, 2, 3, 1, 0, 2, 2, 0, 3, 3, 2,
       0, 2, 3, 0, 0, 0, 0, 3, 2, 0, 0, 1, 2, 2, 0, 1, 2, 0, 1, 0, 0, 0,
       0, 0, 3, 1, 2, 2, 2, 2, 1, 1, 2, 1, 3, 0, 0, 2, 0, 1, 0, 3, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 2, 0, 2, 2, 3, 2, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 3, 1, 0, 2, 2, 2, 1, 0, 0, 1, 0, 0, 2, 3, 0, 2, 3, 1, 0, 1, 1,
       2, 0, 1, 3, 3, 2, 0, 2, 3, 1, 3, 3, 0, 2, 0, 0, 1, 0, 1, 0, 1, 3,
       3, 0, 0, 1, 3, 2, 0, 3, 1, 0, 3, 3, 1, 3, 3, 0, 1, 1, 0, 0, 2, 2,
       0, 0, 2, 2, 3, 1, 0, 0, 3, 1, 3, 1, 1, 2, 1, 3, 3, 3, 0, 2, 0, 0,
       3, 1, 0, 3, 1, 1, 2, 3, 0, 3, 0, 0, 2, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       3, 2, 1, 0, 3, 1, 1, 1, 2, 0, 3, 0, 0, 3, 0, 0, 2, 0, 2, 0, 0, 0,
       2, 2, 1, 3, 1, 0, 3, 2, 0, 1, 0, 1, 0, 0, 2, 0, 1, 1, 0, 2, 1, 0,
       1, 2, 0, 3, 1, 0, 0, 3, 0, 2, 1, 0, 2, 2, 3, 1, 1, 0, 2, 3, 1, 1,
       0, 2, 2, 0, 2, 0, 3, 1, 0, 2, 1, 1, 0, 2, 1, 3, 0, 1, 1, 0, 3, 0,
       0, 1, 2, 3, 3, 2, 0, 0, 1, 0, 3, 0, 3, 0, 1, 3, 2, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 3, 3, 1, 1, 1, 0, 2, 3, 0, 0, 0, 3, 1, 1, 0, 1, 0, 0,
       0, 2, 1, 3, 1, 0, 0, 1, 2, 1, 0, 3, 0, 0, 0, 3, 1, 1, 0, 3, 0, 2,
       0, 0, 0, 0, 2, 3, 0, 1, 2, 0, 3, 2, 3, 0, 2, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 2, 1, 2, 2, 0, 2, 0, 0, 0, 1, 1, 0, 3, 0, 1, 2, 1, 1, 3, 2,
       0, 2, 2, 2, 0, 0, 1, 3, 3, 3, 1, 1, 0, 3, 0, 1])

In [33]:
X["College_level"] = clusters

In [34]:
X

     Student_Faculty_Ratio  Annual_Fees_INR  ...  Infrastructure_Score  College_level
0                       14           113042  ...                     8              2
1                       27           115999  ...                     7              0
2                       22            47955  ...                     9              0
3                       18            67841  ...                     8              0
4                       15           100640  ...                     9              0
..                     ...              ...  ...                   ...            ...
495                     17           106323  ...                     5              1
496                     12            39111  ...                     7              0
497                     16           199182  ...                     3              3
498                     10            46389  ...                     6              0
499                     24           152177  ...                     8              1

[500 rows x 6 columns]

In [37]:
X[X["College_level"] == 1]

     Student_Faculty_Ratio  Annual_Fees_INR  ...  Infrastructure_Score  College_level
5                       28           226582  ...                     4              1
7                       26           220103  ...                     9              1
10                      28           193551  ...                     5              1
15                      28           101180  ...                     3              1
20                      28           216141  ...                     5              1
..                     ...              ...  ...                   ...            ...
481                     15            31605  ...                     4              1
490                     20           188518  ...                     9              1
494                     11            34324  ...                     3              1
495                     17           106323  ...                     5              1
499                     24           152177  ...                     8              1

[134 rows x 6 columns]

In [42]:
X.groupby(by="College_level").agg(['mean'])

              Student_Faculty_Ratio Annual_Fees_INR Placement_Percentage Average_Package_LPA Infrastructure_Score
                               mean            mean                 mean                mean                 mean
College_level
0                         18.078652   111260.651685            66.747191            5.311910             6.966292
1                         23.500000   135924.529851            67.985075            9.136642             5.902985
2                         11.650000   175656.000000            59.790000            8.362500             6.080000
3                         17.159091   156795.136364            85.568182            5.565682             3.965909

In [43]:
X.groupby(by="College_level").agg(["min","max"])

              Student_Faculty_Ratio     Annual_Fees_INR          ... Average_Package_LPA        Infrastructure_Score
                                min max             min     max  ...                 min    max                  min max
College_level                                                    ...
0                                 8  29           30404  246727  ...                2.00  11.68                    3   9
1                                11  29           31062  249536  ...                3.56  11.99                    3   9
2                                 8  20           49065  249930  ...                2.01  11.91                    3   9
3                                 8  29           39337  248803  ...                2.09  11.96                    3   9

[4 rows x 10 columns]

In [44]:
X

     Student_Faculty_Ratio  Annual_Fees_INR  ...  Infrastructure_Score  College_level
0                       14           113042  ...                     8              2
1                       27           115999  ...                     7              0
2                       22            47955  ...                     9              0
3                       18            67841  ...                     8              0
4                       15           100640  ...                     9              0
..                     ...              ...  ...                   ...            ...
495                     17           106323  ...                     5              1
496                     12            39111  ...                     7              0
497                     16           199182  ...                     3              3
498                     10            46389  ...                     6              0
499                     24           152177  ...                     8              1

[500 rows x 6 columns]

In [47]:
cluster_names = {3:"Best college",
                1:"Mid-level college",
                 0:"emerging colleges",
                2:"emerging colleges"}
X["Category"] = X["College_level"].map(cluster_names)

In [48]:
X

     Student_Faculty_Ratio  Annual_Fees_INR  ...  College_level           Category
0                       14           113042  ...              2  emerging colleges
1                       27           115999  ...              0  emerging colleges
2                       22            47955  ...              0  emerging colleges
3                       18            67841  ...              0  emerging colleges
4                       15           100640  ...              0  emerging colleges
..                     ...              ...  ...            ...                ...
495                     17           106323  ...              1  Mid-level college
496                     12            39111  ...              0  emerging colleges
497                     16           199182  ...              3       Best college
498                     10            46389  ...              0  emerging colleges
499                     24           152177  ...              1  Mid-level college

[500 rows x 7 columns]

In [50]:
(X.Category).nunique()

3

# now supervised learning

In [55]:
input_data = X.drop(["College_level","Category"], axis=1)
output_data = X["College_level"]
X_train, X_test, y_train,y_test = train_test_split(input_data,output_data,test_size=0.20,random_state=12,
                                                    shuffle=True,
                                                    stratify=output_data)

In [57]:
X_train.shape, y_train.shape

((400, 5), (400,))

In [58]:
X_test.shape, y_test.shape

((100, 5), (100,))

In [68]:
rf_model = RandomForestClassifier(max_depth=5)
rf_model.fit(X_train,y_train)
y_pred_train = rf_model.predict(X_train)
y_pred_test = rf_model.predict(X_test)
print("Train Accuracy score :", accuracy_score(y_train,y_pred_train))
print("Test Accuracy score :", accuracy_score(y_test,y_pred_test))

Train Accuracy score : 0.9425
Test Accuracy score : 0.85